### ISSUE TITLE
AttributeError: 'float' object has no attribute 'a'

### ISSUE THREAD

**Issue by mustafakhalidcs** [nalepae/pandarallel#102]
Hi, 
I was trying to run this snippet on my mac (Python 3.6.2) 

```
def func(x):
    return math.sin(x.a**2) + math.sin(x.b**2)

df_size = int(5e2)
df = pd.DataFrame(dict(a=np.random.randint(1, 8, df_size),
                       b=np.random.rand(df_size)))

%%time
res_parallel = df.parallel_applymap(func)
```

It throws this exception.

```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/eapple/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/eapple/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandarallel/pandarallel.py", line 59, in global_worker
    return _func(x)
  File "/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandarallel/pandarallel.py", line 143, in wrapper
    **kwargs
  File "/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandarallel/data_types/dataframe.py", line 41, in worker
    return df.applymap(func)
  File "/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandas/core/frame.py", line 6944, in applymap
    return self.apply(infer)
  File "/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandas/core/apply.py", line 296, in apply_standard
    values, self.f, axis=self.axis, dummy=dummy, labels=labels
  File "pandas/_libs/reduction.pyx", line 620, in pandas._libs.reduction.compute_reduction
  File "pandas/_libs/reduction.pyx", line 128, in pandas._libs.reduction.Reducer.get_result
  File "/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandas/core/frame.py", line 6942, in infer
    return lib.map_infer(x.astype(object).values, func)
  File "pandas/_libs/lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "<ipython-input-4-ae12c3a75aca>", line 2, in func
    return math.sin(x.a**2) + math.sin(x.b**2)
AttributeError: 'float' object has no attribute 'a'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-8-a6335fb81304> in <module>
      1 # %%time
----> 2 res_parallel = df.parallel_applymap(func)

/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandarallel/pandarallel.py in closure(data, func, *args, **kwargs)
    455                 input_files,
    456                 output_files,
--> 457                 map_result,
    458             )
    459 

/Workspace/RocketScripts/env/lib/python3.6/site-packages/pandarallel/pandarallel.py in get_workers_result(use_memory_fs, nb_workers, show_progress_bar, nb_columns, queue, chunk_lengths, input_files, output_files, map_result)
    389                 progress_bars.update(progresses)
    390 
--> 391     results = map_result.get()
    392 
    393     return (

~/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

AttributeError: 'float' object has no attribute 'a'
```
Can someone please advise.

Thanks

**Comment by Orpheous1** [comment]
applymap works element-wise, not row or column wise. The elements themselves in this example don't have attributes, they're just floats. The rows have attributes named after the columns, a and b in this example. What you are looking for is probably apply, not applymap.
