### ISSUE TITLE
parallel_apply on empty dataframe fails with confusing error

### ISSUE THREAD

**Issue by zachary-jablons-okcupid** [nalepae/pandarallel#115]
I occasionally have code that should fail earlier because I've accidentally created an empty dataframe, however I've found that `parallel_apply` fails when `apply` does not on these, with an error from `multiprocessing`. I'm not sure if the desired behavior for `parallel_apply` on an empty dataframe is for it to fail, but if it is then it would be nice to have that explicitly handled as it can be rather confusing to figure out what's going on.

Here's a [gist](https://gist.github.com/zachary-jablons-okcupid/9c0e48b0eae286d585443e5030a77f5f) that reproduces this issue, and the error that I get is below:
```
INFO: Pandarallel will run on 48 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
Traceback (most recent call last):
  File "empty_error.py", line 13, in <module>
    pandarallel_apply = empty_df.a.parallel_apply(lambda x: x + 1)
  File "/home/u1/zach/.pyenv/versions/py37/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 447, in closure
    nb_workers, worker_init, (prepare_worker(use_memory_fs)(worker),),
  File "/home/u1/zach/.pyenv/versions/3.7.5/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/u1/zach/.pyenv/versions/3.7.5/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

It's not obvious that this error is due to an empty dataframe. I think what happens is that `nb_workers` is set to `0` [here](https://github.com/nalepae/pandarallel/blob/master/pandarallel/pandarallel.py#L443).

This is on Python 3.7.5 with
```
pandas==1.1.3
pandarallel==1.5.1
```

Thanks,
Zach

**Comment by NanisTe** [comment]
I can agree here. Lost half a day in debugging this because I looked at the wrong spot.

**Comment by guillaumachina** [comment]
Hello,
Even with the version `1.6.5` we still encounter the problem on empty Series / Dataframes:
```python
import pandarallel as plll
import pandas as pd
import pytest
from packaging import version
from pandarallel import pandarallel

def test_pandarallel_version():
    """Test that pandarallel version is at least 1.6.5."""
    
    current_version = version.parse(plll.__version__)
    min_version = version.parse("1.6.5")

    assert current_version >= min_version, f"pandarallel version {plll.__version__} is below minimum required 1.6.5"

def test_parallel_apply_empty_dataframe(empty_dataframe):
    """Test parallel_apply with an empty DataFrame."""
    pandarallel.initialize(nb_workers=2, verbose=2)
    result = pd.DataFrame().parallel_apply(lambda x: x * 2)

    # Assert that the result is empty
    assert result.empty, "Parallel apply should return an empty DataFrame."
```

Here is the error
```
==================================================== FAILURES ====================================================
______________________________________ test_parallel_apply_empty_dataframe _______________________________________

    def test_parallel_apply_empty_dataframe():
        """Test parallel_apply with an empty DataFrame."""
        pandarallel.initialize(nb_workers=2, verbose=2)
>       result = pd.DataFrame().parallel_apply(lambda x: x * 2)

tests/recipe_recommender/dataset/test_pandarallel.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv/test-reco/lib/python3.10/site-packages/pandarallel/core.py:294: in closure
    pool = CONTEXT.Pool(nb_workers)
../../../.pyenv/versions/3.10.16/lib/python3.10/multiprocessing/context.py:119: in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.pool.Pool state=INIT pool_size=0>, processes = 0, initializer = None, initargs = ()
maxtasksperchild = None, context = <multiprocessing.context.ForkContext object at 0x756d2f2fd0c0>

    def __init__(self, processes=None, initializer=None, initargs=(),
                 maxtasksperchild=None, context=None):
        # Attributes initialized early to make sure that they exist in
        # __del__() if __init__() raises an exception
        self._pool = []
        self._state = INIT
    
        self._ctx = context or get_context()
        self._setup_queues()
        self._taskqueue = queue.SimpleQueue()
        # The _change_notifier queue exist to wake up self._handle_workers()
        # when the cache (self._cache) is empty or when there is a change in
        # the _state variable of the thread that runs _handle_workers.
        self._change_notifier = self._ctx.SimpleQueue()
        self._cache = _PoolCache(notifier=self._change_notifier)
        self._maxtasksperchild = maxtasksperchild
        self._initializer = initializer
        self._initargs = initargs
    
        if processes is None:
            processes = os.cpu_count() or 1
        if processes < 1:
>           raise ValueError("Number of processes must be at least 1")
E           ValueError: Number of processes must be at least 1

../../../.pyenv/versions/3.10.16/lib/python3.10/multiprocessing/pool.py:205: ValueError
---------------------------------------------- Captured stdout call ----------------------------------------------
INFO: Pandarallel will run on 2 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
============================================ short test summary info =============================================
FAILED tests/recipe_recommender/dataset/test_pandarallel.py::test_parallel_apply_empty_dataframe - ValueError: Number of processes must be at least 1
1 failed, 4 passed in 0.34s
```

**Comment by Alex17Li** [comment]
1.6.5 doesn't have this feature in it (even though this was merged years ago). A new latest version needs to be pushed to pip.

**Comment by t-muser** [comment]
I merged the PR back in the day, but I don't have access to pypi. @nalepae would need to handle this :)
