### ISSUE TITLE
Exception when using cythonized library

### ISSUE THREAD

**Issue by LuciusV** [nalepae/pandarallel#118]
When I use pandarallel in cythonized .so file, I got

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./runtest.py", line 6, in <module>
    parallel_process()
  File "libtest.py", line 19, in libtest.parallel_process
  File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 462, in closure
    map_result,
  File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 396, in get_workers_result
    results = map_result.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
SystemError: unknown opcode

To reproduce:

1. Create library.py and define any function inside which uses parallel_apply on any pandas dataframe
2. Create run.py, which imports that function from library and runs. It will run normally.
3. cythonize -i  library.py and try to run run.py - it will fail with SystemError: unknown opcode

**Comment by LuciusV** [comment]
There are details from cython github comments: issue is on pandarallel side https://github.com/cython/cython/issues/3908#issuecomment-725924528

**Comment by LuciusV** [comment]
Please share your thoughts is there really no hope to do something with this? :(
