### ISSUE TITLE
[Errno 38] Function not implemented in AWS Lambda

### ISSUE THREAD

**Issue by tho-asterist** [nalepae/pandarallel#128]
I tried to use `pandarallel` in AWS Lambda but got the error

```
File "/opt/python/pandarallel/pandarallel.py", line 446, in closure
    pool = context.Pool(
File "/var/lang/lib/python3.8/multiprocessing/context.py", line 119, in Pool
  return Pool(processes, initializer, initargs, maxtasksperchild,
File "/var/lang/lib/python3.8/multiprocessing/pool.py", line 191, in __init__
  self._setup_queues()
File "/var/lang/lib/python3.8/multiprocessing/pool.py", line 343, in _setup_queues
  self._inqueue = self._ctx.SimpleQueue()
File "/var/lang/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
  return SimpleQueue(ctx=self.get_context())
File "/var/lang/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
  self._rlock = ctx.Lock()
File "/var/lang/lib/python3.8/multiprocessing/context.py", line 68, in Lock
  return Lock(ctx=self.get_context())
File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
  SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
  sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 38] Function not implemented
```

Would anyone have the same issue?

**Comment by galigutta** [comment]
I ran into the exact same issue. Can this issue be re-opened? I got the same last few lines of error.
[ERROR] OSError: [Errno 38] Function not implemented
Traceback (most recent call last):
  File "/var/task/app.py", line 15, in handler
    portfolio = generate_portfolio(params)
  File "/var/task/app.py", line 36, in generate_portfolio
    mindf = Pricer.get_prices_pnl_fcst(ticker, asofdate, est_min, daydf, comps_curr, comps_fut)
  File "/var/task/optionpricer.py", line 168, in get_prices_pnl_fcst
    mindf['model_iv'] = mindf.parallel_apply(Pricer.brentq_wrapper, axis=1)
  File "/var/lang/lib/python3.9/site-packages/pandarallel/core.py", line 408, in closure
    pool = CONTEXT.Pool(nb_workers)
  File "/var/lang/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/var/lang/lib/python3.9/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/var/lang/lib/python3.9/multiprocessing/pool.py", line 343, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/var/lang/lib/python3.9/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/var/lang/lib/python3.9/multiprocessing/queues.py", line 341, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(

**Comment by valbuc** [comment]
seems to be an issue with AWS not supporting multiprocessing:

https://stackoverflow.com/questions/56329799/how-to-emulate-multiprocessing-pool-map-in-aws-lambda
