### ISSUE TITLE
`from time import time_ns` raise ImportError when using python3.6 (same with #38)

### ISSUE THREAD

**Issue by tongyifan** [nalepae/pandarallel#223]
## General

- **Operating System**:
- **Python version**: 3.6
- **Pandas version**: 1.1.5
- **Pandarallel version**: 1.6.4

## Acknowledgement

- [x] My issue is **NOT** present when using `pandas` without alone (without `pandarallel`)
- [x] If I am on **Windows**, I read the [Troubleshooting page](https://nalepae.github.io/pandarallel/troubleshooting/)
      before writing a new bug report

### Observed behavior

```
Traceback (most recent call last):
  File "...", line 273, in <module>
    robot.validate()
  File "...", line 7, in validate
    if not validator.validate():
  File "...", line 76, in validate
    from pandarallel import pandarallel
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/pandarallel/__init__.py", line 1, in <module>
    from .core import pandarallel
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/pandarallel/core.py", line 26, in <module>
    from .progress_bars import ProgressBarsType, get_progress_bars, progress_wrapper
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/pandarallel/progress_bars.py", line 8, in <module>
    from time import time_ns
ImportError: cannot import name 'time_ns'
```

### Expected behavior

return nothing(import successfully)

## Minimal but working code sample to ease bug fix for `pandarallel` team

```python
from pandarallel import pandarallel
```

**Comment by till-m** [comment]
Hey @tongyifan,

thanks for reporting this bug.

I think the move here is to add Python 3.7 as minimum requirement for pandarallel. Python 3.6 actually reached EoL [a year ago](https://endoflife.date/python).
