### ISSUE TITLE
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'

### ISSUE THREAD

**Issue by NeuroWinter** [nalepae/pandarallel#31]
I can't seem to get pandarallel to work with one of my functions.

The function uses a lot of other modules like Spacy, nltk, and numpy and is quite a complex function, hence why I want to run it in parallel.

This is the line that is causing the error in the title:
``` data.body = data.body.parallel_apply(super().remove_noise, progress_bar=False)```

and this is the full traceback:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'
```

And then the program just hangs. 
Any help would be much appreciated.

**Comment by NeuroWinter** [comment]
Turns out this is a problem with spacy: https://github.com/explosion/thinc/issues/53 https://github.com/explosion/spaCy/issues/1669 
Upgrading to `spacy==2.1.4` fixed my issue.
