### ISSUE TITLE
groupby and apply does not work

### ISSUE THREAD

**Issue by JonasRSV** [nalepae/pandarallel#49]
```python

def cumulate_asset_scores(dataset):
    dataset['counts'] = list(range(len(dataset)))
    dataset['corrects'] = dataset['score'].cumsum()
    return dataset
    

from pandarallel import pandarallel

pandarallel.initialize(progress_bar=True, shm_size_mb=30000)
df = dataframe.groupby('user_id').parallel_apply(cumulate_asset_scores)

```

yields

```bash
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/usr/local/lib/python3.7/site-packages/pandarallel/dataframe_groupby.py", line 15, in worker
    df = client.get(object_id)
  File "pyarrow/_plasma.pyx", line 579, in pyarrow._plasma.PlasmaClient.get
  File "pyarrow/_plasma.pyx", line 572, in pyarrow._plasma.PlasmaClient.get
  File "pyarrow/serialization.pxi", line 470, in pyarrow.lib.deserialize
  File "pyarrow/serialization.pxi", line 433, in pyarrow.lib.deserialize_from
  File "pyarrow/serialization.pxi", line 275, in pyarrow.lib.SerializedPyObject.deserialize
  File "pyarrow/serialization.pxi", line 183, in pyarrow.lib.SerializationContext._deserialize_callback
  File "/usr/local/lib/python3.7/site-packages/pyarrow/serialization.py", line 175, in _deserialize_pandas_dataframe
    return pdcompat.serialized_dict_to_dataframe(data)
  File "/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 640, in serialized_dict_to_dataframe
    for block in data['blocks']]
  File "/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 640, in <listcomp>
    for block in data['blocks']]
  File "/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 661, in _reconstruct_block
    dtype = make_datetimetz(item['timezone'])
  File "/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 676, in make_datetimetz
    return _pandas_api.datetimetz_type('ns', tz=tz)
TypeError: 'NoneType' object is not callable
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-12-6a762afbe0c2> in <module>
      2 
      3 pandarallel.initialize(shm_size_mb=30000)
----> 4 df = dataframe.groupby('user_id').parallel_apply(cumulate_asset_scores)
      5 #res = []
      6 #for _, g in tqdm.tqdm(list(dataframe.groupby('user_id'))):

/usr/local/lib/python3.7/site-packages/pandarallel/utils.py in wrapper(*args, **kwargs)
     78             """Please see the docstring of this method without `parallel`"""
     79             try:
---> 80                 return func(*args, **kwargs)
     81 
     82             except _PlasmaStoreFull:

/usr/local/lib/python3.7/site-packages/pandarallel/dataframe_groupby.py in closure(df_grouped, func, *args, **kwargs)
     36             with ProcessingPool(nb_workers) as pool:
     37                 result_workers = pool.map(
---> 38                     DataFrameGroupBy.worker, workers_args)
     39 
     40             if len(df_grouped.grouper.shape) == 1:

/usr/local/lib/python3.7/site-packages/pathos/multiprocessing.py in map(self, f, *args, **kwds)
    135         AbstractWorkerPool._AbstractWorkerPool__map(self, f, *args, **kwds)
    136         _pool = self._serve()
--> 137         return _pool.map(star(f), zip(*args)) # chunksize
    138     map.__doc__ = AbstractWorkerPool.map.__doc__
    139     def imap(self, f, *args, **kwds):

/usr/local/lib/python3.7/site-packages/multiprocess/pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

/usr/local/lib/python3.7/site-packages/multiprocess/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

TypeError: 'NoneType' object is not callable

```

In a jupyter notebook

**Comment by kkawabat** [comment]
can you give a sample of what dataframe is i.e. 

`dataframe.head()`

**Comment by nalepae** [comment]
Could you please try again with `pandarallel v1.4.5` and tell me if this issue still occurs?
