### ISSUE TITLE
ValueError: Shape of passed values is (7, 5), indices imply (1003, 5)

### ISSUE THREAD

**Issue by tobdub** [nalepae/pandarallel#70]
```
df_grouped = df_p.groupby([pd.Grouper(key="datetime", freq="21s"), "topic"])
df_p = df_grouped.parallel_apply(process_tag_wrapper, org=org)
```

Data sample:

```
topic            payload   timestamp  datetime
glg/c100200010b7 b'...'    1578441727 2020-01-08 00:02:07
```

Traceback (most recent call last):
  File "eval.py", line 39, in <module>
    evaluate(ORG, args.date, PERIOD, args.nrows)
  File "/app/tests/evaluate.py", line 160, in evaluate
    df_e = perform_positioning(df_e, org, stats)
  File "/app/tests/evaluate.py", line 121, in perform_positioning
    df_p = df_grouped.parallel_apply(process_tag_wrapper, org=org)
  File "/usr/local/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 449, in closure
    return reduce(results, reduce_meta_args)
  File "/usr/local/lib/python3.7/site-packages/pandarallel/data_types/dataframe_groupby.py", line 28, in reduce
    index=index,
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 462, in __init__
    mgr = arrays_to_mgr(arrays, columns, index, columns, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 87, in arrays_to_mgr
    return create_block_manager_from_arrays(arrays, arr_names, axes)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1699, in create_block_manager_from_arrays
    construction_error(len(arrays), arrays[0].shape, axes, e)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1719, in construction_error
    "Shape of passed values is {0}, indices imply {1}".format(passed, implied)
ValueError: Shape of passed values is (7, 5), indices imply (1003, 5)

**Comment by nalepae** [comment]
Could you please try with `pandarallel v1.4.5` and tell me if this issue still occurs?

**Comment by nalepae** [comment]
I close this issue.
Feel free to reopen it if you still encounter it with the last version of **Pandarallel**.
